### PR TITLE
Create OTPLocker

### PR DESCRIPTION
**Pull request by MewTww**
VaultBank.io

### CODE REVIEW

**Comment by ChrisCates** [comment]
@MewTww, you okay Brett?

**Comment by MewTww** [comment]
Is this Chris Cates or Martin Shkreli?...

**Comment by MewTww** [comment]
I tried to buy Palantir through GitHub Aquisi coding...

**Comment by MewTww** [comment]
If this is Chris Cates then how the fuck did you know this is me>???>>>>

**Comment by MewTww** [comment]
---------- Forwarded message ---------
From: Gregory Brett Faucher <vaultbancltd@gmail.com>
Date: Sun, Oct 25, 2020 at 10:38 AM
Subject: Re: [ChrisCates/OTPLocker] Create OTPLocker (#10)
To: ChrisCates/OTPLocker <
reply@reply.github.com>


If this is Chris Cates then how the fuck did you know this is me>???>>>>

**Pull request closed without merging**
